services:
  AshjerTracker:
    container_name: AshjerTracker
    build: .
    restart: unless-stopped
    command: ["python", "core.py"]
    volumes:
      - logs:/app/Logs
      - jobs:/app/jobs
      - db_dumps:/app/db_dumps
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/postgresql/:/var/run/postgresql/
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - COC_API_EMAIL
      - COC_API_PASSWORD
      - COC_API_KEY_COUNT
      - COC_API_KEY_NAME
      - DB_HOST
      - DB_PORT
      - DB_DATABASE
      - DB_USER
      - DB_PASSWORD
      - DISCORD_APP_ID
      - DISCORD_BOT_INVITE
      - DISCORD_BOT_TOKEN
      - DISCORD_BOT_WEBHOOK
      - DISCORD_OAUTH_CLIENT_ID
      - DISCORD_OAUTH_CLIENT_SECRET
      - DISCORD_PUBLIC_KEY
      - DISCORD_WEBHOOK_LOG_URL
      - DISCORD_WEBHOOK_LB_LOG_URL
      - DISCORD_WEBHOOK_ERROR_URL
      - PERMISSION_LEVEL_DEV
      - PERMISSION_LEVEL_MANAGER
      - PERMISSION_TRUSTED_SERVERS
      - PRODUCTION
    env_file:
      - path: ./.env
        required: false

volumes:
  logs:
    name: "AshjerTracker Logs"
  jobs:
    name: "AshjerTracker Jobs"
  db_dumps:
    name: "AshjerTracker db_dumps"